### ISSUE TITLE
Use CSS capabilities to detect odd and even elements

### ISSUE THREAD

**Issue by ClemRz** [queraul/pagina-playlist#6]
Read https://www.w3.org/Style/Examples/007/evenodd.en.html

**Comment by queraul** [comment]
i don't know how can i use this in my code because it doesn't have tables. i tried to use with the divs but it doesn't work, they colored randomly. What can i do?

**Comment by ClemRz** [comment]
You need to check that your selector is pointing to the correct set of `divs`. I'm absolutely sure you can use it.

**Comment by ClemRz** [comment]
Looks good now 👍

closing.
